apply plugin: 'com.android.application'

android {
    namespace "com.bigjelly.temporun"
    compileSdk 36

    defaultConfig {
        applicationId "com.bigjelly.temporun"
        minSdk 23
        targetSdk 36
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'com.android.support:appcompat-v7:22.2.0'
    implementation 'org.jetbrains.kotlin:kotlin-stdlib:2.2.10'
}
