apply plugin: 'com.android.application'
apply plugin: 'org.jetbrains.kotlin.plugin.compose'

android {
    namespace "com.bigjelly.temporun"
    compileSdk 36

    buildFeatures {
        compose true
        prefab true
    }

    ndkVersion "28.2.13676358"

    externalNativeBuild {
        cmake {
            path file("src/main/cpp/CMakeLists.txt")
        }
    }

    defaultConfig {
        applicationId "com.bigjelly.temporun"
        minSdk 23
        targetSdk 36
        versionCode 1
        versionName "1.0"

        externalNativeBuild {
            cmake {
                cppFlags "-std=c++17"
                arguments "-DANDROID_STL=c++_shared"
            }
        }
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation 'org.jetbrains.kotlin:kotlin-stdlib:2.2.10'
    implementation platform('androidx.compose:compose-bom:2025.08.00')
    implementation 'androidx.activity:activity-compose:1.10.1'
    implementation 'androidx.compose.ui:ui'
    implementation 'androidx.compose.ui:ui-tooling-preview'
    implementation 'androidx.compose.material3:material3'
    implementation 'com.google.oboe:oboe:1.9.3'
    debugImplementation 'androidx.compose.ui:ui-tooling'
}
